### PR TITLE
DELIGHT gentx

### PR DESCRIPTION
**Pull request by psy2848048**

### CODE REVIEW

**Review by ejfitzgerald — CHANGES_REQUESTED** [review]
Hi,

It looks like you have not used the [Token Bridge](https://token-bridge.fetch.ai/) in order to transfer your FET across to the native network. We will not be able to accept your gentx unless you make a transfers. To not do so might result in differences between the total supplies between the two networks.

Please feel free to discuss here or we can discuss in private on the discord channel!

**Comment by psy2848048** [comment]
image

With this problem, I've already talked with Jon and the number was the discussed. Please check it and tell me the number if I need a change.

**Comment by psy2848048** [comment]
@ejfitzgerald I pushed as 1 FET, with the number from Jon. Could you please check it?

**Review by ejfitzgerald — APPROVED** [review]
Looks good thanks

**Pull request merged**
